### ISSUE TITLE
Scroll bar seemingly not appearing

### ISSUE THREAD

**Issue by 0x150** [lukflug/PanelStudio#17]
Either i am blatantly retarded or the scroll bar just... does not show up at all

**Comment by ChompChompDead** [comment]
scroll bar for what? scrolling on gui or a panel

**Comment by lukflug** [comment]
Have you overriden the `getScrollHeight` method for the `DraggableContainer` instances? Are you using `GameSenseTheme` with an nonzero scroll bar width?

**Comment by 0x150** [comment]
I am using the gamesense theme with a nonzero scroll bar width, and did not override the method.

**Comment by lukflug** [comment]
Yes, since you didn't override that method, the scroll height is equal to the total height of the container. There is only scrolling when the scroll height is bigger than the height of the container.
![image](https://user-images.githubusercontent.com/47392064/114305353-16bc8880-9ad8-11eb-820e-dac7a847da28.png)
